#!/usr/bin/env bash
# Install nginx on a remote server using SSH
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx restart