#!/usr/bin/env bash
# Redirect to a page when requested
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
sudo service nginx restart
