#!/usr/bin/env bash

if [ "$1" ]; then
    mysqldump -u root -p"$1" --all-databases > backup.sql
    tar -czvf $"(date "+%d-%m-%Y")".tar.gz backup.sql
else
    echo "Usage: ./5-mysql_backup <password>"
fi
